//=========================================================
// src/BBsynth2_main.c: generated by Hardware Configurator
//
// This file will be updated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!!
//=========================================================

//-----------------------------------------------------------------------------
// Includes
//-----------------------------------------------------------------------------
#include <SI_EFM8BB1_Register_Enums.h>                  // SFR declarations
#include "InitDevice.h"
// $[Generated Includes]
// [Generated Includes]$

//-----------------------------------------------------------------------------
// SiLabs_Startup() Routine
// ----------------------------------------------------------------------------
// This function is called immediately after reset, before the initialization
// code is run in SILABS_STARTUP.A51 (which runs before main() ). This is a
// useful place to disable the watchdog timer, which is enable by default
// and may trigger before main() in some instances.
//-----------------------------------------------------------------------------
void SiLabs_Startup (void)
{
  // $[SiLabs Startup]
  // [SiLabs Startup]$
}
extern unsigned int step;

// equal tempered scale C5 to C6
#define C5 (0)
#define Cs5 (1)
#define D5 (2)
#define Ds5 (3)
#define E5 (4)
#define F5 (5)
#define Fs5 (6)
#define G5 (7)
#define Gs5 (8)
#define A5 (9)
#define As5 (10)
#define B5 (11)


code unsigned int scale[12]={
488,  //C5 523 Hertz
460,  //Cs5
435, // D5
410, //Ds5
387, //E5
365, // F5
345, // Fs5
326, // G5
307, // Gs5
290, //A5 880 Hertz
274, //As5
258,  //B5
};

//-----------------------------------------------------------------------------
// main() Routine
// ----------------------------------------------------------------------------
int main (void)
{
	unsigned int i,keys;
  // Call hardware initialization routine
  enter_DefaultMode_from_RESET();
  step=0;
  while (1) 
  {
    // $[Generated Run-time code]
    // [Generated Run-time code]$
	keys=(P2&1)+(P0&0xfe)+((P1&0xf)<<8);
//	if (!P2_B0) step=scale[0];
//	else if (!P0_B1)step=scale[1];
//	else step=0;
	for (i=0;i<12;i++){
		if (!(keys&(1<<i))){
			step=scale[i];
			break;
		}//if
	}//for
	if (i==12){
		step=0;
		P0_B0=1;
	}//if
  }//while
}//main()
